apiVersion: v1
kind: Secret
metadata:
  name: orbitx-secrets
  namespace: orbitx
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://orbitx:orbitx_production_password@orbitx-postgres-service:5432/orbitx_db"
  JWT_SECRET_KEY: "orbitx-k8s-cluster-jwt-signing-secret-key-production-32chars!"
  POSTGRES_PASSWORD: "orbitx_production_password"
